<a href="https://colab.research.google.com/github/karthiksivakoti/ML-For-Beginners/blob/main/PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
torch.__version__

'2.2.1+cu121'

In [ ]:
print("I am excited to run this")

I am excited to run this


In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.1+cu121


# **Introduction to Tensors**

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
# vector
vector = torch.tensor([7, 7])
vector
#vector.ndim
#vector.item()

tensor([7, 7])

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# Matrix
MATRIX = torch.tensor([[7, 8],[9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]
MATRIX[1]

tensor([ 9, 10])

In [ ]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],[3,6,9], [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

# RANDOM TENSOR

In [ ]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.4414, 0.7681, 0.8385, 0.3166],
        [0.0468, 0.5812, 0.0670, 0.9173],
        [0.2959, 0.3276, 0.7411, 0.4643]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_tensor.shape

torch.Size([3, 4])

In [ ]:
random_tensor.size()

torch.Size([3, 4])

In [ ]:
random_image_tensor = torch.rand(size=(3, 224, 224)) #color channels, height, width
random_image_tensor.ndim, random_image_tensor.shape

(3, torch.Size([3, 224, 224]))

In [ ]:
random_tensor_ofownsize = torch.rand(size=(5,10,10))
random_tensor_ofownsize.ndim, random_tensor_ofownsize.shape


(3, torch.Size([5, 10, 10]))

Zeroes and Ones tensor

In [ ]:
zero = torch.zeros(size=(3, 4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zero*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(3, 4))
ones


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
ones*zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

Range of Tensors, Tensor - like

In [ ]:
one_to_ten = torch.arange(start = 1, end = 11, step = 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor Datatypes

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0,9.0], dtype = None, device = None, requires_grad = False)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [ ]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9], dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
int_32_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
x = torch.arange(0,100,10)

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
x.min()

tensor(0)

In [ ]:
x.max()

tensor(90)

In [ ]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [ ]:
x.type(torch.float32).mean()

tensor(45.)

In [ ]:
x.sum()

tensor(450)

In [ ]:
x.argmax()

tensor(9)

In [ ]:
x.argmin()

tensor(0)

In [ ]:
x[0]

tensor(0)

In [ ]:
x[9]

tensor(90)

In [ ]:
x = torch.arange(1, 10)
x.shape

torch.Size([9])

In [ ]:
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [ ]:
x_reshaped.view(1,9)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
x_stacked = torch.stack([x, x, x, x], dim = 1)
x_stacked

tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8],
        [9, 9, 9, 9]])

In [ ]:
x_stacked.squeeze()

tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8],
        [9, 9, 9, 9]])

In [ ]:
x_stacked.unsqueeze(dim=1)

tensor([[[1, 1, 1, 1]],

        [[2, 2, 2, 2]],

        [[3, 3, 3, 3]],

        [[4, 4, 4, 4]],

        [[5, 5, 5, 5]],

        [[6, 6, 6, 6]],

        [[7, 7, 7, 7]],

        [[8, 8, 8, 8]],

        [[9, 9, 9, 9]]])

In [ ]:
x_stacked.squeeze()

tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8],
        [9, 9, 9, 9]])

In [ ]:
x_stacked.unsqueeze(dim=-2)

tensor([[[1, 1, 1, 1]],

        [[2, 2, 2, 2]],

        [[3, 3, 3, 3]],

        [[4, 4, 4, 4]],

        [[5, 5, 5, 5]],

        [[6, 6, 6, 6]],

        [[7, 7, 7, 7]],

        [[8, 8, 8, 8]],

        [[9, 9, 9, 9]]])

In [ ]:
import torch
tensor = torch.tensor([1, 2, 3])
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [ ]:
torch.mul(tensor, 10)

tensor([-90, -80, -70])

In [ ]:
torch.sub(tensor, 100)

tensor([-109, -108, -107])

In [ ]:
torch.add(tensor, 100)

tensor([91, 92, 93])

In [ ]:
torch.divide(tensor, 2)

tensor([-4.5000, -4.0000, -3.5000])

In [ ]:
torch.matmul(tensor, tensor)

tensor(194)

In [ ]:
tensor@tensor

tensor(194)

In [ ]:
%%time
tensor@tensor

CPU times: user 622 µs, sys: 0 ns, total: 622 µs
Wall time: 516 µs


tensor(194)

In [ ]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 424 µs, sys: 998 µs, total: 1.42 ms
Wall time: 1.43 ms


tensor(194)

In [ ]:
torch.rand(3,2)

tensor([[0.5999, 0.0073],
        [0.9321, 0.3026],
        [0.3463, 0.3872]])

In [ ]:
torch.matmul(torch.rand(3,2), torch.rand(2,3))

tensor([[0.3528, 0.1893, 0.0714],
        [1.2791, 0.7110, 0.2563],
        [0.8812, 0.4553, 0.1803]])

In [1]:
import torch

In [2]:
x = torch.rand(2,9)

In [3]:
x

tensor([[0.5894, 0.4391, 0.2018, 0.5417, 0.3844, 0.3592, 0.9209, 0.9269, 0.0681],
        [0.0746, 0.1740, 0.6821, 0.6890, 0.0999, 0.7444, 0.2391, 0.4625, 0.8302]])

In [5]:
y=torch.randn(2,3,5)
y

tensor([[[ 1.5552, -0.4877,  0.5175, -1.7958, -0.6187],
         [-0.3359, -1.9710,  0.0112, -1.7578, -1.5295],
         [ 0.0932,  1.4079,  0.9108,  0.3328, -0.6978]],

        [[-0.9406, -1.0809, -0.2595,  0.1282,  1.6605],
         [ 1.1624,  1.0902,  1.7092, -0.2842, -1.3780],
         [-0.1534, -1.2795, -0.5495,  0.9902,  0.1822]]])

In [6]:
x_original = torch.rand(size=(224,224,3))
x_original

tensor([[[0.4549, 0.6809, 0.2118],
         [0.4824, 0.9008, 0.8741],
         [0.1715, 0.1757, 0.1845],
         ...,
         [0.8741, 0.6594, 0.2610],
         [0.0092, 0.1984, 0.1955],
         [0.4236, 0.4182, 0.0251]],

        [[0.9174, 0.1661, 0.5852],
         [0.1837, 0.2351, 0.3810],
         [0.3726, 0.4808, 0.8732],
         ...,
         [0.6794, 0.0554, 0.9202],
         [0.0864, 0.8750, 0.3558],
         [0.8445, 0.9759, 0.4934]],

        [[0.1600, 0.2635, 0.7194],
         [0.9488, 0.3405, 0.3647],
         [0.6683, 0.5168, 0.9592],
         ...,
         [0.0521, 0.0140, 0.2445],
         [0.3596, 0.3999, 0.2730],
         [0.5926, 0.9877, 0.7784]],

        ...,

        [[0.4794, 0.5635, 0.3764],
         [0.9124, 0.6094, 0.5059],
         [0.4528, 0.4447, 0.5021],
         ...,
         [0.0089, 0.4816, 0.8727],
         [0.2173, 0.6296, 0.2347],
         [0.2028, 0.9931, 0.7201]],

        [[0.3116, 0.6459, 0.4703],
         [0.0148, 0.2345, 0.7149],
         [0.

In [9]:
x_permuted=x_original.permute(2, 0, 1)
print(x_original.shape)
print(x_permuted.shape)

torch.Size([224, 224, 3])
torch.Size([3, 224, 224])


In [10]:
x_original[0,0,0]

tensor(0.4549)

In [11]:
x_permuted[0,0,0]

tensor(0.4549)

In [13]:
x_original[0,0,0]=0.989

In [14]:
x_original[0,0,0]

tensor(0.9890)

In [15]:
x_permuted[0,0,0]

tensor(0.9890)

In [18]:
x=torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [19]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [21]:
x[0][0]

tensor([1, 2, 3])

In [22]:
x[0][0][0]

tensor(1)

In [23]:
x[0][2][2]

tensor(9)

In [24]:
x[:,1,1]

tensor([5])

In [25]:
x[0,0,:]

tensor([1, 2, 3])

In [26]:
x[0,:,2]

tensor([3, 6, 9])

In [27]:
import numpy as np

In [28]:
array = np.arange(1.0, 8.0)

In [29]:
array

array([1., 2., 3., 4., 5., 6., 7.])

In [32]:
tensor = torch.from_numpy(array)
tensor

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

In [33]:
array[3]=11.0

In [34]:
array

array([ 1.,  2.,  3., 11.,  5.,  6.,  7.])

In [35]:
tensor

tensor([ 1.,  2.,  3., 11.,  5.,  6.,  7.], dtype=torch.float64)

In [37]:
tensor = torch.ones(7)
tensor, tensor.dtype
numpy_tensor = tensor.numpy()
numpy_tensor, numpy_tensor.dtype

(array([1., 1., 1., 1., 1., 1., 1.], dtype=float32), dtype('float32'))

In [38]:
import torch
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.9870, 0.6636, 0.6873, 0.8863],
        [0.8386, 0.4169, 0.3587, 0.0265],
        [0.2981, 0.6025, 0.5652, 0.5840]])
tensor([[0.9821, 0.3481, 0.0913, 0.4940],
        [0.7495, 0.4387, 0.9582, 0.8659],
        [0.5064, 0.6919, 0.0809, 0.9771]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [46]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [2]:
!nvidia-smi

Thu May 23 02:57:59 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   60C    P8              11W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [3]:
import torch
torch.cuda.is_available()

True

In [5]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [6]:
torch.cuda.device_count()

1

In [7]:
tensor = torch.tensor([1,2,3], device = "cpu")
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [8]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [10]:
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [12]:
tensor_on_cpu = tensor_on_gpu.cpu().numpy()