### Welcome to the world of Machine learning
###### create the .venv environment form https://scikit-learn.org/stable/install.html
###### use the .venv environment for the execution of the ipykernel
###### first install scikit-learn, matplotlib, numpy, pandas, ipykernel in virtual environment

In [7]:
import numpy as np
a = np.array([
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]
    ],
    [
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]
    ]   
])
print("Shape:", a.shape)
print("3D Array: \n", a)

Shape: (2, 3, 4)
3D Array: 
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
